version: '3.8'

services:
  backend:
    build: .
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app
      - UVICORN_FORWARDED_ALLOW_IPS=*
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - cache_data:/app/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:stable
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro

volumes:
  cache_data:
